version: "3.8"
services:
  # Contenedor para la base de datos
  db:
    image: mongo:7.0.5-jammy
    container_name: db-lizard
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=myPassword123
    ports:
      - 27017:27017
    volumes:
      - mongodb_lizard:/data/db
      - mongodb_config_lizard:/data/configdb
    networks:
      - lizard_net

  # Contenedor para la API
  api:
    container_name: api-lizard
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./api:/code/
    ports:
      - "8000:80"

    depends_on:
      - db
    networks:
      - lizard_net

networks:
  lizard_net:
volumes:
  mongodb_lizard:
  mongodb_config_lizard:
